name: Deploy no Hostgator

on:
  push:
    branches: [ main ]  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: ðŸšš Atualizar cÃ³digo
      uses: actions/checkout@v2

    - name: Definir versÃ£o do nove Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: ðŸ”¨ Build Project
      run: CI=false npm run build

    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.ftp_host }}
        username: ${{ secrets.s6_ftp_user }}
        password: ${{ secrets.s6_ftp_password }}
        local-dir: testes/build 
        publish-dir: ./build
